### ISSUE TITLE
[layout] Cuts 44px after landing at the bottom

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/switcher#2]
Landing is fine, but when you switch page, it cuts 44px at the bottom of the window canvas.

![image](https://cloud.githubusercontent.com/assets/962224/13679034/fd3eaa04-e6f1-11e5-8e6a-94c64ab20119.png)

![image](https://cloud.githubusercontent.com/assets/962224/13679077/308f1dee-e6f2-11e5-8a81-f2fb2eb49f82.png)

**Comment by jimdebeer** [comment]
what is the size of the topbar?

**Comment by nikoloza** [comment]
@jimdebeer 44px for normal apps and 44px + 20px for native ios apps (~23px for native android).

**Comment by jimdebeer** [comment]
could this relate to the fixes made for the ios scroll bug?

**Comment by nikoloza** [comment]
@jimdebeer no it's about switcher. maybe I'll move it to there

**Comment by jimdebeer** [comment]
@youzi can you check this later this week?

**Comment by youzi** [comment]
@jimdebeer @nikoloza It's most probably something with the switcher switching to `position:absolute` for it's children when animating pages. I'll take a look end of this week.
